spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: admin
    password: admin
    h2:
      console:
        debug: true
  h2:
    console:
      enabled: true #http://localhost:8080/h2-console
